# -*- coding: utf-8 -*-
"""生成 流行病学问卷（禽流感病例）字段定义 JSON。
用法: python3 make_lx_json.py  -> 输出 lx_fields.json
"""
import json

sections = [
    ("FIRSTUNIT", "一、病例的发现/报告情况"),
    ("NAME", "二、病例一般情况"),
    ("ONSETDT", "三、病例的发病与就诊经过"),
    ("FIRSTSYM", "四、病例的临床表现"),
    ("ENVDESC", "五、病例居住环境及暴露情况"),
    ("HOMEPOS", "六、病例家居环境情况"),
    ("HANDWASH", "七、病例生活习惯、既往健康史"),
    ("TOUCHANI", "八、病例发病前的暴露情况"),
    ("CLOSENAME", "九、密切接触者情况（具体见附件4中的表2）"),
    ("BLD1DT", "十、实验室检查"),
    ("FINALDIAG", "十一、转归与最终诊断情况"),
    ("SURVUNIT", "十二、调查小结"),
]
sections = [{"field": f, "title": t} for f, t in sections]

F = []
def add(name, ftype, label, **kw):
    d = {"name": name, "type": ftype, "label": label}
    d.update(kw)
    F.append(d)

YN1 = {"options": ["【1】有", "【2】无"], "digits": 1}
YN2 = {"options": ["【1】是", "【2】否"], "digits": 1}
YN3 = {"options": ["【1】是", "【2】否", "【3】不知道"], "digits": 1}

# ---- 一、病例的发现/报告情况 ----
add("FIRSTUNIT", "text", "1.病例的首次发现单位(具体到科室)", length=15)
add("TEL1", "text", "1.1联系方式：(1)电话", length=15)
add("FAX", "text", "(2)传真", length=15)
add("EMAIL", "text", "(3)E-mail", length=20)
add("FOUNDDT", "date", "1.2发现日期")
add("FOUNDTM", "time", "发现时间")
add("REPUNIT", "text", "2.首次报告单位", length=15)
add("RECVUNIT", "text", "2.1接到报告单位", length=15)
add("REPWAY", "number", "2.2报告方式", digits=1, options=["【1】电话", "【2】传真", "【3】E-mail", "【4】网络直报", "【5】其它"])
add("REPWAYO", "text", "【5】其它", length=8)
add("REPDT", "date", "2.3报告日期")
add("REPTM", "time", "报告时间")
add("REPDISE", "text", "2.4报告疾病名称", length=15)
add("NETREP", "number", "3.首次报告时，是否进行网络直报", **YN2)
add("NETREPU", "text", "3.1若进行网络直报，报告单位为", length=15)
add("NETREPDT", "date", "3.2报告日期")
add("NETREPTM", "time", "报告时间")
add("NETREPD", "text", "3.3报告疾病名称", length=15)

# ---- 二、病例一般情况 ----
add("NAME", "text", "1.病例姓名", length=4)
add("PNAME", "text", "家长姓名(若是儿童，请填写)", length=4)
add("SEX", "number", "2.性别", **{"options": ["【1】男", "【2】女"], "digits": 1})
add("NATION", "text", "3.民族", length=6)
add("BIRTHDT", "date", "4.出生日期")
add("AGE", "number", "实足年龄（岁，出生日期不详时填写）", digits=3)
add("AGEM", "number", "实足年龄（月，出生日期不详时填写）", digits=2)
add("IDCARD", "text", "5.身份证号码（或家长身份证号码）", length=18)
add("HUJI", "text", "6.户籍", length=25)
add("ADDRESS", "text", "7.现住址", length=25)
add("WORKUNIT", "text", "8.学习或工作单位", length=15)
add("MOBILE", "text", "9.联系电话：(1)手机", length=15)
add("HOMETEL", "text", "(2)家庭电话", length=15)
add("OTHTEL", "text", "(3)其它联系人电话", length=15)
add("OCCUP", "number", "10.职业", digits=2, options=["【1】幼托儿童", "【2】散居儿童", "【3】学生", "【4】教师", "【5】保育保姆", "【6】餐饮业", "【7】商业服务", "【8】工人", "【9】民工", "【10】农民", "【11】牧民", "【12】渔(船)民", "【13】干部职员", "【14】离退人员", "【15】家务", "【16】待业", "【17】医疗机构工作人员", "【18】其他"])
add("OCCUPO", "text", "【18】其他", length=8)

# ---- 三、病例的发病与就诊经过 ----
add("ONSETDT", "date", "1.发病日期")
add("ONSETPL", "number", "2.发病地点", digits=1, options=["【1】家中", "【2】单位", "【3】其他"])
add("ONSETPO", "text", "【3】其他", length=8)
add("SELFMED", "number", "3.前往医疗机构就诊前，是否自行服药", **YN3)
add("MEDKIND", "text", "3.1若自行服药，则服药种类", length=10)
for i in range(1, 7):
    add(f"VISIT{i}U", "text", f"第{i}次就诊单位", length=10)
    add(f"VISIT{i}D", "date", f"第{i}次 就诊日期")
    add(f"VISIT{i}T", "number", f"第{i}次 治疗天数", digits=2)
    add(f"VISIT{i}R", "text", f"第{i}次 诊断结果", length=10)
    add(f"VISIT{i}I", "number", f"第{i}次 是否隔离", **YN2)
    add(f"VISIT{i}H", "text", f"第{i}次 入住院时间", length=8)
    add(f"VISIT{i}M", "text", f"第{i}次 门诊/住院病历号", length=10)
    add(f"VISIT{i}O", "text", f"第{i}次 转归", length=6)

# ---- 四、病例的临床表现 ----
add("FIRSTSYM", "text", "1.首发症状(描述)", length=20)
add("FEVER", "number", "2.流感样表现：发热", **YN1)
add("TEMPRANGE", "text", "体温(范围)℃", length=10)
add("FEVERTM", "text", "发热持续时间", length=10)
add("CHILL", "number", "寒战", **YN1)
add("COUGH", "number", "咳嗽", **YN1)
add("SPUTUM", "number", "咳痰", **YN1)
add("SORETHROAT", "number", "咽痛", **YN1)
add("HEADACHE", "number", "头痛", **YN1)
add("NASALSTUFF", "number", "鼻塞", **YN1)
add("RUNNYNOSE", "number", "流涕", **YN1)
add("MUSCLEACH", "number", "肌肉酸痛", **YN1)
add("JOINTACH", "number", "关节酸痛", **YN1)
add("FATIGUE", "number", "乏力", **YN1)
add("CHESTTIGHT", "number", "胸闷", **YN1)
add("DYSPNEA", "number", "气促", **YN1)
add("BREATHDIFF", "number", "呼吸困难", **YN1)
add("DIARRHEA", "number", "腹泻", **YN1)
add("CONJUNCTIV", "number", "结膜炎", **YN1)
add("OTHSYMP", "text", "3.其它临床表现(描述)", length=20)

# ---- 五、病例居住环境及暴露情况 ----
add("ENVDESC", "text", "1.病例居住地点(村庄/居民楼)周围环境描述", length=25)
add("LIVEMARKET", "number", "2.周围3公里内是否有：活禽市场", **YN1)
add("AGROMARKET", "number", "农贸市场", **YN1)
add("FEEDFARM", "number", "饲养场", **YN1)
add("NATLAKE", "number", "天然湖泊", **YN1)
add("ARTLAKE", "number", "人工湖", **YN1)
add("RIVER", "number", "河流", **YN1)
add("BROOK", "number", "小溪", **YN1)
add("WETLAND", "number", "湿地", **YN1)
add("MARSH", "number", "沼泽", **YN1)
add("ENVNONE", "number", "均无", **YN1)
add("ENVOTH", "number", "其它", **YN1)
add("ENVOTHO", "text", "其它注明", length=8)
add("BIRDS", "number", "3.是否能见到候鸟或野禽", digits=1, options=["【1】经常见到", "【2】偶然见到", "【3】从未见过", "【4】不知道", "【5】其它"])
add("BIRDSO", "text", "【5】其它", length=8)
add("DEADBIRD", "number", "4.近期是否有死亡候鸟或野禽", **YN3)
add("DEADBPL", "text", "4.1若有，常见地点", length=10)
add("DEADBDT", "date", "4.2候鸟或野禽最近死亡日期")
add("ANIMALH", "number", "5.病例居住地点动物饲养或病死情况", **YN2)
add("FARMNAME", "text", "养殖场名称", length=10)
add("ANIMKIND", "text", "动物种类", length=6)
add("RAISENUM", "number", "饲养数量", digits=4)
add("SICKNUM", "number", "病/死数量", digits=4)
add("SICKTM", "text", "病/死时间", length=8)
add("DEALWAY", "text", "处理方式", length=10)
add("DEALTM", "text", "处理时间", length=8)
add("DEALPERS", "number", "参与处理人员数量", digits=3)
add("HOUSTOT", "number", "6.家禽饲养户人员情况，总户数", digits=4)
add("POPTOT", "number", "总人口数", digits=4)
add("POPRES", "number", "常住人口", digits=4)
add("FARMHOUS", "number", "饲养家禽户数", digits=4)
add("FARMHOP", "number", "饲养家禽户人口数", digits=4)
add("DEADHOUS", "number", "病死家禽户数", digits=4)
add("DEADHOP", "number", "病死家禽户人口数", digits=4)
add("ABNPERS", "number", "异常表现人数(流感样病例/发热性疾病等)", digits=4)
add("FARMNAME2", "text", "7.养殖场名称（若居住地有养殖场）", length=10)
add("FARMKIND2", "text", "饲养动物种类及数量", length=10)
add("FARMSICK2", "text", "病/死动物种类及数量", length=10)
add("H5N1CONF", "number", "8.农业部门是否已经证实死亡家禽死于H5N1型禽流感", digits=1, options=["【1】是", "【2】否", "【3】证实中", "【4】不知道"])
add("POSITYPE", "text", "8.1分离(PCR)阳性标本类型", length=10)
add("COLLPL", "text", "采集地点", length=10)
add("COLLTM", "text", "采集时间", length=8)
add("SEPTM", "text", "分离时间", length=8)
add("SEPUNIT", "text", "分离单位", length=10)
add("DISINF", "number", "9.当地环境是否已经进行彻底消毒", **YN3)
add("DISINTM", "date", "9.1若已经彻底消毒，则时间为")
add("OTHCASE", "number", "10.有病死动物后，当地有无流感样/发热/不明原因死亡病例等", **YN3)
add("CASENAME", "text", "10.1病例姓名", length=4)
add("CASESEX", "number", "性别", **{"options": ["【1】男", "【2】女"], "digits": 1})
add("CASEAGE", "number", "年龄", digits=3)
add("CASESYM", "text", "临床表现", length=10)
add("CASEDT", "text", "发病/死亡时间", length=8)
add("CASEACTM", "text", "有无接触及时间", length=10)
add("CASEREM", "text", "备注", length=10)

# ---- 六、病例家居环境情况 ----
add("HOMEPOS", "text", "1.描述病例家庭位置(位置/附近水源等情况)", length=25)
add("HOMETYPE", "number", "2.病例家庭", digits=1, options=["【1】围墙院落", "【2】半封闭院落", "【3】敞开式院落", "【4】其它"])
add("HOMETYPEO", "text", "【4】其它", length=8)
add("HOUSETYPE", "number", "3.病人家居住房类型", digits=1, options=["【1】平房", "【2】独立楼房", "【3】公寓", "【4】其它"])
add("HOUSETYPEO", "text", "【4】其它", length=8)
add("FLOORTYPE", "number", "4.房屋地板类型", digits=1, options=["【1】瓷砖", "【2】木地板", "【3】土地", "【4】其它"])
add("FLOORTYPEO", "text", "【4】其它", length=8)
add("CLEANFREQ", "text", "5.多长时间打扫一次房间", length=10)
add("CUTBOARD", "number", "6.家中厨房菜板使用", digits=1, options=["【1】生肉/熟食加工分开", "【2】生肉/熟食混用"])
add("CUTBOARDW", "number", "6.1若混用菜板，则加工完生肉类后", digits=1, options=["【1】每次均清洗", "【2】偶尔清洗1次", "【3】从不清洗"])
add("FLUKNOW", "number", "7.家庭成员的禽流感知识知晓情况", digits=1, options=["【1】明白", "【2】听说过", "【3】从不知道", "【4】其它"])
add("FLUKNOWO", "text", "【4】其它", length=8)
add("FLUKSRC", "number", "7.1若明白，则知识来于", digits=1, options=["【1】电视", "【2】报纸", "【3】广播", "【4】宣传单", "【5】入户宣传", "【6】其它"])
add("FLUKSRCO", "text", "【6】其它", length=8)
for i in range(1, 4):
    add(f"POUL{i}K", "text", f"8.家中禽类饲养情况：第{i}种 动物种类", length=6)
    add(f"POUL{i}N", "number", f"第{i}种 饲养数量", digits=4)
    add(f"POUL{i}T", "text", f"第{i}种 饲养时间", length=8)
    add(f"POUL{i}R", "number", f"第{i}种 活动范围", digits=1, options=["【1】仅圈内", "【2】院内", "【3】卧室内", "【4】厨房", "【5】厕所", "【6】院外", "【7】其它"])
    add(f"POUL{i}F", "number", f"第{i}种 动物粪便可见范围", digits=1, options=["【1】圈内", "【2】院内", "【3】卧室", "【4】厨房", "【5】厕所", "【6】其它"])
add("PENPOS", "number", "9.家禽圈位置", digits=1, options=["【1】室外", "【2】厕所内", "【3】厨房内", "【4】人居住房间", "【5】无人居住房间", "【6】单独禽舍", "【7】其他"])
add("PENPOSD", "text", "家禽圈与病例居住房间关系描述", length=10)
add("DEADANK", "text", "10.病死动物情况：动物种类", length=6)
add("DEADANN", "number", "饲养数量", digits=4)
add("DEADANM", "number", "病死数量", digits=4)
add("DEADANT", "text", "发病/死亡时间", length=8)
add("DEADANR", "text", "死亡原因", length=10)
add("DEADANW", "text", "处理方式", length=10)
add("H5N1CF2", "number", "11.农业部门是否证实病死动物死于H5N1型禽流感", **YN3)
add("SAMPKIND", "text", "11.1环境/病死禽畜采样种类", length=10)
add("SAMPTM", "text", "采样时间", length=8)
add("SAMPPL", "text", "采样地点", length=10)
add("SAMPNUM", "number", "采样份数", digits=4)
add("SAMPRSLT", "text", "检测结果", length=10)
add("SAMPUNIT", "text", "检测单位", length=10)
add("HOMEDIS", "number", "12.家庭环境是否进行彻底消毒", **YN3)
add("HOMEDISTM", "date", "12.1若已经彻底消毒，则时间为")
for i in range(1, 6):
    add(f"MEM{i}N", "text", f"13.家庭成员及与病死动物接触方式：第{i}位 姓名", length=4)
    add(f"MEM{i}S", "number", f"第{i}位 性别", **{"options": ["【1】男", "【2】女"], "digits": 1})
    add(f"MEM{i}A", "number", f"第{i}位 年龄", digits=3)
    add(f"MEM{i}I", "number", f"第{i}位 发病与否", **YN2)
    add(f"MEM{i}K", "text", f"第{i}位 接触病死动物种类", length=10)
    add(f"MEM{i}W", "number", f"第{i}位 接触病死动物方式", digits=1, options=["【1】饲养", "【2】打扫禽舍", "【3】宰杀", "【4】烹饪", "【5】食用", "【6】无"])

# ---- 七、病例生活习惯、既往健康史 ----
add("HANDWASH", "number", "1.饭前洗手", digits=1, options=["【1】每次均洗手", "【2】偶尔洗手", "【3】从不洗手", "【4】其它"])
add("HANDWASO", "text", "【4】其它", length=8)
add("SMOKE", "number", "2.是否抽烟", **YN2)
add("SMOKENUM", "number", "3.1若抽烟，每天几支", digits=1, options=["【1】1-4支", "【2】5-9支", "【3】10-20支", "【4】20支以上"])
add("CHR01", "number", "4.慢性疾病（医生已诊断，可多选）：哮喘", **YN1)
add("CHR02", "number", "慢性支气管炎", **YN1)
add("CHR03", "number", "其它慢性肺部疾病", **YN1)
add("CHR04", "number", "冠心病", **YN1)
add("CHR05", "number", "糖尿病", **YN1)
add("CHR06", "number", "肾病", **YN1)
add("CHR07", "number", "免疫缺陷", **YN1)
add("CHR08", "number", "其它慢性疾病", **YN1)
add("CHR08O", "text", "其它慢性疾病注明", length=8)
add("FLUVAC", "number", "5.一年内是否接种流感疫苗", **YN2)
add("FLUVACDT", "text", "5.1如有，最后一次接种日期", length=10)
add("IMMGLB", "number", "6.是否曾注射免疫球蛋白", digits=1, options=["【1】是", "【2】否", "【3】记不清"])
add("IMMGLBDT", "text", "6.1如有，最后一次接种日期", length=10)

# ---- 八、病例发病前的暴露情况 ----
add("TOUCHANI", "number", "1.病前2周内是否接触禽类及其它动物", **YN3)
add("TOUCHCK", "number", "1.1接触动物种类：鸡", **YN1)
add("TOUCHDK", "number", "鸭", **YN1)
add("TOUCHGK", "number", "鹅", **YN1)
add("TOUCHWK", "number", "野禽", **YN1)
add("TOUCHOTH", "number", "其它", **YN1)
add("TOUCHOTHO", "text", "其它注明", length=8)
add("TOUW01", "number", "1.2接触方式：饲养", **YN1)
add("TOUW02", "number", "打扫、清洗禽舍", **YN1)
add("TOUW03", "number", "接触动物分泌物", **YN1)
add("TOUW04", "number", "购买加工生鲜禽肉", **YN1)
add("TOUW05", "number", "职业运输", **YN1)
add("TOUW06", "number", "收集或运输禽类粪便", **YN1)
add("TOUW07", "number", "收集或卖鸡蛋", **YN1)
add("TOUW08", "number", "清洗禽毛", **YN1)
add("TOUW09", "number", "买卖活禽", **YN1)
add("TOUW10", "number", "宰杀禽类", **YN1)
add("TOUW11", "number", "食用", **YN1)
add("TOUW12", "number", "处理/掩埋禽类", **YN1)
add("TOUCHTM", "text", "1.3接触时间", length=15)
add("TOUCHWASH", "number", "1.4接触家禽后是否洗手", digits=1, options=["【1】每次均洗", "【2】偶尔洗一次", "【3】从不洗手"])
add("PLFARM", "number", "1.5若未接触过禽类及其它动物，病前2周内是否到过：饲养场", **YN1)
add("PLMARK", "number", "农贸市场", **YN1)
add("PLWATER", "number", "河/湖/塘边", **YN1)
add("PLWET", "number", "湿地", **YN1)
add("PLPARK", "number", "公园", **YN1)
add("PLOTH", "number", "其它", **YN1)
add("PLOTHO", "text", "其它注明", length=8)
add("TOUCHDEAD", "number", "2.病前2周内是否接触病死禽类", **YN3)
add("DEADK1", "number", "2.1接触种类：鸡", **YN1)
add("DEADK2", "number", "鸭", **YN1)
add("DEADK3", "number", "鹅", **YN1)
add("DEADK4", "number", "野禽", **YN1)
add("DEADK5", "number", "未接触", **YN1)
add("DEADK6", "number", "不清楚", **YN1)
add("DEADK7", "number", "其它", **YN1)
add("DEADK7O", "text", "其它注明", length=8)
add("DEADW1", "number", "2.2接触方式：宰杀、加工病死动物", **YN1)
add("DEADW2", "number", "接触病死禽排泄物", **YN1)
add("DEADW3", "number", "接触病死禽分泌物", **YN1)
add("DEADW4", "number", "直接接触病死禽", **YN1)
add("DEADW5", "number", "食用病死禽肉", **YN1)
add("DEADW6", "number", "其它", **YN1)
add("DEADW6O", "text", "其它注明", length=8)
add("DEADTM", "text", "2.3接触时间", length=15)
add("COOKED", "number", "2.4若食用病死禽肉，则所食用时是否熟透", **YN3)
add("SLAU1", "number", "3.参与宰杀、加工病死禽类主要方式：捕捉或固定病死禽类", **YN1)
add("SLAU2", "number", "烫洗死禽", **YN1)
add("SLAU3", "number", "拔除禽毛", **YN1)
add("SLAU4", "number", "接触死禽血液", **YN1)
add("SLAU5", "number", "清洗/接触死禽内脏", **YN1)
add("SLAU6", "number", "刀切病死禽肉", **YN1)
add("SLAU7", "number", "清洗、处理禽肉", **YN1)
add("WOUND", "number", "3.1接触病死禽期间，手部伤口情况", digits=1, options=["【1】无伤口", "【2】未愈合旧伤口", "【3】处理过程造成伤口"])
add("PRO1", "number", "3.2防护措施：带手套", **YN1)
add("PRO2", "number", "穿防护鞋", **YN1)
add("PRO3", "number", "带口罩", **YN1)
add("PRO4", "number", "服用抗病毒药物", **YN1)
add("PRO5", "number", "无任何防护措施", **YN1)
add("SLAUWASH", "number", "3.3处理病死禽后是否洗手", digits=1, options=["【1】每次均洗", "【2】偶尔洗一次", "【3】从不洗手", "【4】其它"])
add("SLAUWASO", "text", "【4】其它", length=8)
add("FEVERCONT", "number", "4.发病前2周内是否与其它发热病人有所接触", **YN3)
add("FCNAME", "text", "4.1接触病例姓名", length=4)
add("FCDT", "text", "发病时间", length=8)
add("FCSYM", "text", "临床表现", length=10)
add("FCDIAG", "text", "诊断", length=10)
add("FCLAST", "text", "最后接触时间", length=8)
add("FCWAY", "text", "接触方式及频率", length=10)
add("FCPL", "text", "接触地点", length=10)
add("MASK", "number", "4.2若在医院接触病人，是否戴口罩", **YN2)
add("VISITWASH", "number", "4.3若看望病人，看望病人后是否洗手", **YN2)
add("LABVISIT", "number", "5.发病前2周内，是否到过禽流感病毒学实验室", **YN2)
add("LABPRO", "number", "5.1若曾到过实验室，是否进行防护", **YN2)
add("TRIPFROM", "text", "6.病例旅行史：旅行起始地", length=10)
add("TRIPTM", "text", "旅行时间", length=10)
add("TRIPTO", "text", "旅行目的地", length=10)
add("TRIPOTH", "text", "发病地点以外所到地区情况", length=15)

# ---- 九、密切接触者情况 ----
add("CLOSENAME", "text", "姓名", length=4)
add("CLOSESEX", "number", "性别", **{"options": ["【1】男", "【2】女"], "digits": 1})
add("CLOSEREL", "text", "与患者关系", length=6)
add("CLOSETEL", "text", "联系电话", length=15)

# ---- 十、实验室检查 ----
for i in range(1, 4):
    add(f"BLD{i}DT", "text", f"1.血常规：第{i}次检查日期", length=8)
    add(f"BLD{i}WBC", "number", f"第{i}次 WBC(×10^9/L)", digits="3.1")
    add(f"BLD{i}N", "number", f"第{i}次 N(%)", digits=3)
    add(f"BLD{i}L", "number", f"第{i}次 L(%)", digits=3)
    add(f"BLD{i}U", "text", f"第{i}次 检测单位", length=10)
for i in range(1, 4):
    add(f"XRAY{i}DT", "text", f"2.X线检查：第{i}次检查日期", length=8)
    add(f"XRAY{i}RS", "text", f"第{i}次 结果", length=10)
    add(f"XRAY{i}U", "text", f"第{i}次 检测单位", length=10)
for i in range(1, 3):
    add(f"CT{i}DT", "text", f"3.CT检查：第{i}次检查日期", length=8)
    add(f"CT{i}RS", "text", f"第{i}次 结果", length=10)
    add(f"CT{i}U", "text", f"第{i}次 检测单位", length=10)
add("SPECIMEN", "text", "4.病原学和血清学检查：标本类型", length=10)
add("COLLTM2", "text", "采集时间", length=8)
add("TESTMETH", "text", "检测方法", length=10)
add("TESTRSLT", "text", "检测结果", length=10)
add("TESTUNIT", "text", "检测单位", length=10)
add("TESTTM", "text", "检测时间", length=8)

# ---- 十一、转归与最终诊断情况 ----
add("FINALDIAG", "number", "1.最终诊断", digits=1, options=["【1】确诊病例", "【2】疑似病例", "【3】临床诊断病例", "【4】排除(病名：)"])
add("FINALDIAGO", "text", "排除的病名", length=10)
add("DIAGUNIT", "text", "2.诊断单位", length=10)
add("OUTCOME", "number", "3.转归", digits=1, options=["【1】痊愈", "【2】死亡", "【3】其他"])
add("OUTCOMEO", "text", "【3】其他", length=8)
add("DISCHDT", "text", "3.1若痊愈，出院日期", length=8)
add("DEATHDT", "text", "3.2若死亡，死亡日期", length=8)
add("DEATHCAUSE", "text", "死亡原因", length=10)

# ---- 十二、调查小结 ----
add("SURVUNIT", "text", "调查单位", length=15)
add("SURVDT", "text", "调查时间", length=15)
add("SURVNAME", "text", "调查者签名", length=4)

data = {"title": "附表1 流行病学调查表（禽流感病例）", "sections": sections, "fields": F}
with open("/home/user/Doubao/chats/38442199985563650/epidata_work/lx_fields.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=1)
names = [x["name"] for x in F]
dup = [n for n in set(names) if names.count(n) > 1]
long = [n for n in names if len(n) > 10]
print(f"字段总数: {len(F)}  重复: {dup if dup else '无'}  超长: {long if long else '无'}")
